<?php

/**
 * Contains generic functions for this module.
 */

/**
 *
 */
function tcrop_configure_get_modules($include_prereqs = FALSE) {
	$module_prereqs = [
		'libraries',
		'advanced_help', 'ctools date', 'dragndrop_upload', 'ds', 'entity',
		'field_formatter_class', 'field_formatter_settings',
		'field_group', 'field_group_table', 'jquery_update', 'link', 'maillog',
		'panels', 'queue_ui', 'redirect', 'services', 'ultimate_cron', 'views', 'webform',
		'tripal', 'tripal_chado', 'tripal_ws', 'tripal_ds',
	];
	$modules = [
		'chado_custom_search', 'trpfancy_fields', 'tripald3', 'trpdownload_api',
		'analyzedphenotypes', 'divseek_search', 'nd_genotypes', 'tripal_elasticsearch',
		'tripal_galaxy', 'tripal_jbrowse_page', 'tripal_jbrowse_mgmt',
		'tripal_qtl', 'vcf_filter', 'tripal_germplasm_importer', 'tripal_map'
	];

	if ($include_prereqs) {
		return array_merge($module_prereqs, $modules);
	}
	else {
		return $modules;
	}
}
